spring:
  application:
    name: emailService
  zipkin:
    base-url: http://212.64.11.93:9411
server:
  port: 8989
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://212.64.11.93:8761/eureka/,http://111.231.66.26:8761/eureka/