spring:
  application:
    name: zipkin
server:
  port: 9411
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://212.64.11.93:8761/eureka/,http://111.231.66.26:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false