spring:
  application:
    name: eureka
  zipkin:
    base-url: http://212.64.11.93:9411
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
    ip-address: 111.231.66.26
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://212.64.11.93:${server.port}/eureka