spring:
  application:
    name: eureka
  boot:
    admin:
      client:
        url: http://212.64.11.93:8084
        instance:
          prefer-ip: true
  zipkin:
    base-url: http://212.64.11.93:9411
server:
  port: 8761
eureka:
  instance:
    ip-address: 212.64.11.93
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://111.231.66.26:${server.port}/eureka
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info