spring:
  application:
    name: feign
  boot:
    admin:
      client:
        url: http://212.64.11.93:8084
        instance:
          prefer-ip: true
          management-base-url: http://${eureka.instance.ip-address}:${server.port}
          service-base-url: http://${eureka.instance.ip-address}:${server.port}
  zipkin:
    base-url: http://212.64.11.93:9411
server:
  port: 8766
eureka:
  instance:
    ip-address: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://212.64.11.93:8761/eureka/,http://111.231.66.26:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
feign:
  hystrix:
    enabled: true
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:7777/oauth/token_key
    client:
      client-id: feign_client
      client-secret: longqi.123
      access-token-uri: http://localhost:7777/oauth/token
      grant-type: password,refresh_token
      scope: server
      user-authorization-uri: http://localhost:7777/oauth/authorize