spring:
  application:
    name: admin
  zipkin:
    base-url: http://212.64.11.93:9411
server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://212.64.11.93:8761/eureka/,http://111.231.66.26:8761/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
